on:
  pull_request:
    paths:
      - 'docs/src/site/**'
      - 'docs/build.gradle'
      - 'gradle/**'

jobs:
  check-doc-build:
    name: netCDF-Java Documentation Build Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build docs using Gradle
        run: ./gradlew buildJekyllSite
      - if: success()
        name: Upload a preview of the rendered html
        uses: actions/upload-artifact@v2
        with:
          name: documentation_${{ github.sha }}
          path: docs/build/site
